FROM almalinux:9
# RUN dnf install -y nginx
# CMD ["nginx", "-g", "daemon off;"]
LABEL maintainer="balaji@example.com" \
      build-date="2026-08-09" 
ENV environment="Dev" \
    date="13/08/26"
ADD https://raw.githubusercontent.com/daws-86s/notes/refs/heads/main/session-52.txt /var/temp/52